language: objective-c
rvm:
  - 1.9.3
env:
  global:
    - KIF_SCREENSHOTS="${TRAVIS_BUILD_DIR}/Screenshots/${TRAVIS_BUILD_NUMBER}"
    - secure: N0tEZ7I8Flu1LPxHqG2a4hdZsq/i/X3nz3vbFZWdO9OW9PAm2BXh6Ndqp0W2CyKTnHuLt1l+6RvoaHW9UxHjpSElYcTHB7f61XDV6ldQ6JCk/B2V9z90imKbBN0v1yijjCN2qYSzwV6vAi+QEMyRyFTUKAKanQAng0cUfFsgT00=
  matrix:
    - TEST_SDK=iphonesimulator5.1 SIMULATOR=ipad
    - TEST_SDK=iphonesimulator6.1 SIMULATOR=ipad
    - TEST_SDK=iphonesimulator7.0 SIMULATOR=iphone
    - TEST_SDK=iphonesimulator7.0 SIMULATOR=ipad
before_install:
  - brew update
  - brew install s3cmd
before_script:
  - mkdir -p $KIF_SCREENSHOTS
script:
  - xctool test -test-sdk $TEST_SDK -simulator $SIMULATOR
after_failure:
  - echo "secret_key = $AWS_SECRET" >> .s3cfg
  - s3cmd put --guess-mime-type --config=.s3cfg $KIF_SCREENSHOTS/* s3://travis-iopensongs/$TRAVIS_JOB_NUMBER/
