language: objective-c
rvm:
  - 1.9.3
env:
  global:
    - LANG=en_US.UTF-8
    - KIF_SCREENSHOTS="${TRAVIS_BUILD_DIR}/Screenshots/${TRAVIS_BUILD_NUMBER}"
    - secure: GskcRn321xx1pWm3Hq+ZjZHjONTErXbmM72tsxdafQy9oo0Qjy9LuQeRkQndQgeBbm6RM5Dre/dRSkuTWM89qdaz6aehZ75PPiDIh4qqqX1Pyxq+r9ZQb4GDd1fEVM+vklowhx/l7Ifk0mI3qALcOGIYlo4XOuD/RS3Bqud91i0=
  matrix:
    - TEST_SDK=iphonesimulator6.1 SIMULATOR=ipad
    - TEST_SDK=iphonesimulator7.0 SIMULATOR=iphone
    - TEST_SDK=iphonesimulator7.0 SIMULATOR=ipad
before_install:
  - gem install cocoapods # update to newest version
  - brew update
  - brew install s3cmd
  - brew upgrade xctool
before_script:
  - mkdir -p $KIF_SCREENSHOTS
script:
  - xctool --version
  - xctool test -test-sdk $TEST_SDK -simulator $SIMULATOR
after_failure:
  - echo "secret_key = $AWS_SECRET" >> .s3cfg
  - s3cmd put --guess-mime-type --config=.s3cfg $KIF_SCREENSHOTS/* s3://travis-iopensongs/$TRAVIS_JOB_NUMBER/
