language: objective-c
rvm:
- 1.9.3
env:
- TEST_SDK=iphonesimulator5.1 SIMULATOR=iphone
- TEST_SDK=iphonesimulator5.1 SIMULATOR=ipad
- TEST_SDK=iphonesimulator6.1 SIMULATOR=iphone
- TEST_SDK=iphonesimulator6.1 SIMULATOR=ipad
script:
- xctool test -test-sdk $TEST_SDK -simulator $SIMULATOR
